[package]
name = "my_first_os"
version = "0.1.0"
edition = "2021"
[dependencies]
bootloader = "0.9.23"

[build-dependencies]
bootimage = "0.10.2"

[package.metadata.bootimage]
default-target = "x86_64-unknown-none"
